package com.amiyasahu.spm.dao;

import com.amiyasahu.spm.model.Ofice;
import com.amiyasahu.spm.model.OficeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OficeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offices
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    long countByExample(OficeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offices
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    int deleteByExample(OficeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offices
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    int deleteByPrimaryKey(String officecode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offices
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    int insert(Ofice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offices
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    int insertSelective(Ofice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offices
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    List<Ofice> selectByExample(OficeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offices
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    Ofice selectByPrimaryKey(String officecode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offices
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    int updateByExampleSelective(@Param("record") Ofice record, @Param("example") OficeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offices
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    int updateByExample(@Param("record") Ofice record, @Param("example") OficeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offices
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    int updateByPrimaryKeySelective(Ofice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offices
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    int updateByPrimaryKey(Ofice record);
}