package com.amiyasahu.spm.dao;

import com.amiyasahu.spm.model.ProductLine;
import com.amiyasahu.spm.model.ProductLineExample;
import com.amiyasahu.spm.model.ProductLineWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductLineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    long countByExample(ProductLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    int deleteByExample(ProductLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    int deleteByPrimaryKey(String productline);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    int insert(ProductLineWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    int insertSelective(ProductLineWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    List<ProductLineWithBLOBs> selectByExampleWithBLOBs(ProductLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    List<ProductLine> selectByExample(ProductLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    ProductLineWithBLOBs selectByPrimaryKey(String productline);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    int updateByExampleSelective(@Param("record") ProductLineWithBLOBs record, @Param("example") ProductLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") ProductLineWithBLOBs record, @Param("example") ProductLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    int updateByExample(@Param("record") ProductLine record, @Param("example") ProductLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    int updateByPrimaryKeySelective(ProductLineWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    int updateByPrimaryKeyWithBLOBs(ProductLineWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    int updateByPrimaryKey(ProductLine record);
}