package com.amiyasahu.spm.model;

public class Ofice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offices.officeCode
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    private String officecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offices.city
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offices.phone
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offices.addressLine1
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    private String addressline1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offices.addressLine2
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    private String addressline2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offices.state
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offices.country
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offices.postalCode
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    private String postalcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offices.territory
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    private String territory;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offices.officeCode
     *
     * @return the value of offices.officeCode
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public String getOfficecode() {
        return officecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offices.officeCode
     *
     * @param officecode the value for offices.officeCode
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public void setOfficecode(String officecode) {
        this.officecode = officecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offices.city
     *
     * @return the value of offices.city
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offices.city
     *
     * @param city the value for offices.city
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offices.phone
     *
     * @return the value of offices.phone
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offices.phone
     *
     * @param phone the value for offices.phone
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offices.addressLine1
     *
     * @return the value of offices.addressLine1
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public String getAddressline1() {
        return addressline1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offices.addressLine1
     *
     * @param addressline1 the value for offices.addressLine1
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public void setAddressline1(String addressline1) {
        this.addressline1 = addressline1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offices.addressLine2
     *
     * @return the value of offices.addressLine2
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public String getAddressline2() {
        return addressline2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offices.addressLine2
     *
     * @param addressline2 the value for offices.addressLine2
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public void setAddressline2(String addressline2) {
        this.addressline2 = addressline2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offices.state
     *
     * @return the value of offices.state
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offices.state
     *
     * @param state the value for offices.state
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offices.country
     *
     * @return the value of offices.country
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offices.country
     *
     * @param country the value for offices.country
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offices.postalCode
     *
     * @return the value of offices.postalCode
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public String getPostalcode() {
        return postalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offices.postalCode
     *
     * @param postalcode the value for offices.postalCode
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offices.territory
     *
     * @return the value of offices.territory
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public String getTerritory() {
        return territory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offices.territory
     *
     * @param territory the value for offices.territory
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public void setTerritory(String territory) {
        this.territory = territory;
    }
}