package com.amiyasahu.spm.model;

public class OrderDetailKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetails.orderNumber
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    private Integer ordernumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetails.productCode
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    private String productcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetails.orderNumber
     *
     * @return the value of orderdetails.orderNumber
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public Integer getOrdernumber() {
        return ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetails.orderNumber
     *
     * @param ordernumber the value for orderdetails.orderNumber
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public void setOrdernumber(Integer ordernumber) {
        this.ordernumber = ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetails.productCode
     *
     * @return the value of orderdetails.productCode
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public String getProductcode() {
        return productcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetails.productCode
     *
     * @param productcode the value for orderdetails.productCode
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public void setProductcode(String productcode) {
        this.productcode = productcode;
    }
}