package com.amiyasahu.spm.model;

import java.math.BigDecimal;
import java.util.Date;

public class Payment extends PaymentKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.paymentDate
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    private Date paymentdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.amount
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    private BigDecimal amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.paymentDate
     *
     * @return the value of payments.paymentDate
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public Date getPaymentdate() {
        return paymentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.paymentDate
     *
     * @param paymentdate the value for payments.paymentDate
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public void setPaymentdate(Date paymentdate) {
        this.paymentdate = paymentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.amount
     *
     * @return the value of payments.amount
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.amount
     *
     * @param amount the value for payments.amount
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
}