package com.amiyasahu.spm.model;

import java.util.ArrayList;
import java.util.List;

public class ProductLineExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table productlines
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table productlines
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table productlines
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public ProductLineExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table productlines
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProductlineIsNull() {
            addCriterion("productLine is null");
            return (Criteria) this;
        }

        public Criteria andProductlineIsNotNull() {
            addCriterion("productLine is not null");
            return (Criteria) this;
        }

        public Criteria andProductlineEqualTo(String value) {
            addCriterion("productLine =", value, "productline");
            return (Criteria) this;
        }

        public Criteria andProductlineNotEqualTo(String value) {
            addCriterion("productLine <>", value, "productline");
            return (Criteria) this;
        }

        public Criteria andProductlineGreaterThan(String value) {
            addCriterion("productLine >", value, "productline");
            return (Criteria) this;
        }

        public Criteria andProductlineGreaterThanOrEqualTo(String value) {
            addCriterion("productLine >=", value, "productline");
            return (Criteria) this;
        }

        public Criteria andProductlineLessThan(String value) {
            addCriterion("productLine <", value, "productline");
            return (Criteria) this;
        }

        public Criteria andProductlineLessThanOrEqualTo(String value) {
            addCriterion("productLine <=", value, "productline");
            return (Criteria) this;
        }

        public Criteria andProductlineLike(String value) {
            addCriterion("productLine like", value, "productline");
            return (Criteria) this;
        }

        public Criteria andProductlineNotLike(String value) {
            addCriterion("productLine not like", value, "productline");
            return (Criteria) this;
        }

        public Criteria andProductlineIn(List<String> values) {
            addCriterion("productLine in", values, "productline");
            return (Criteria) this;
        }

        public Criteria andProductlineNotIn(List<String> values) {
            addCriterion("productLine not in", values, "productline");
            return (Criteria) this;
        }

        public Criteria andProductlineBetween(String value1, String value2) {
            addCriterion("productLine between", value1, value2, "productline");
            return (Criteria) this;
        }

        public Criteria andProductlineNotBetween(String value1, String value2) {
            addCriterion("productLine not between", value1, value2, "productline");
            return (Criteria) this;
        }

        public Criteria andTextdescriptionIsNull() {
            addCriterion("textDescription is null");
            return (Criteria) this;
        }

        public Criteria andTextdescriptionIsNotNull() {
            addCriterion("textDescription is not null");
            return (Criteria) this;
        }

        public Criteria andTextdescriptionEqualTo(String value) {
            addCriterion("textDescription =", value, "textdescription");
            return (Criteria) this;
        }

        public Criteria andTextdescriptionNotEqualTo(String value) {
            addCriterion("textDescription <>", value, "textdescription");
            return (Criteria) this;
        }

        public Criteria andTextdescriptionGreaterThan(String value) {
            addCriterion("textDescription >", value, "textdescription");
            return (Criteria) this;
        }

        public Criteria andTextdescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("textDescription >=", value, "textdescription");
            return (Criteria) this;
        }

        public Criteria andTextdescriptionLessThan(String value) {
            addCriterion("textDescription <", value, "textdescription");
            return (Criteria) this;
        }

        public Criteria andTextdescriptionLessThanOrEqualTo(String value) {
            addCriterion("textDescription <=", value, "textdescription");
            return (Criteria) this;
        }

        public Criteria andTextdescriptionLike(String value) {
            addCriterion("textDescription like", value, "textdescription");
            return (Criteria) this;
        }

        public Criteria andTextdescriptionNotLike(String value) {
            addCriterion("textDescription not like", value, "textdescription");
            return (Criteria) this;
        }

        public Criteria andTextdescriptionIn(List<String> values) {
            addCriterion("textDescription in", values, "textdescription");
            return (Criteria) this;
        }

        public Criteria andTextdescriptionNotIn(List<String> values) {
            addCriterion("textDescription not in", values, "textdescription");
            return (Criteria) this;
        }

        public Criteria andTextdescriptionBetween(String value1, String value2) {
            addCriterion("textDescription between", value1, value2, "textdescription");
            return (Criteria) this;
        }

        public Criteria andTextdescriptionNotBetween(String value1, String value2) {
            addCriterion("textDescription not between", value1, value2, "textdescription");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table productlines
     *
     * @mbg.generated do_not_delete_during_merge Sun Sep 18 20:00:15 IST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table productlines
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}