package com.amiyasahu.spm.model;

public class ProductLine {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productlines.productLine
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    private String productline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productlines.textDescription
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    private String textdescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productlines.productLine
     *
     * @return the value of productlines.productLine
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public String getProductline() {
        return productline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productlines.productLine
     *
     * @param productline the value for productlines.productLine
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public void setProductline(String productline) {
        this.productline = productline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productlines.textDescription
     *
     * @return the value of productlines.textDescription
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public String getTextdescription() {
        return textdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productlines.textDescription
     *
     * @param textdescription the value for productlines.textDescription
     *
     * @mbg.generated Sun Sep 18 20:00:15 IST 2016
     */
    public void setTextdescription(String textdescription) {
        this.textdescription = textdescription;
    }
}